DROP INDEX "order_items_order_idx";
DROP INDEX "order_items_product_idx";
DROP INDEX "order_items_variant_idx";
DROP INDEX "orders_user_idx";
DROP INDEX "orders_checkout_session_idx";
DROP INDEX "orders_fulfillment_ref_idx";
DROP INDEX "orders_status_idx";
DROP INDEX "pc_product_idx";
DROP INDEX "pc_collection_idx";
DROP INDEX "product_id_idx";
DROP INDEX "type_idx";
DROP INDEX "variant_product_idx";
DROP INDEX "variant_sku_idx";
DROP INDEX "variant_external_idx";
DROP INDEX "products_public_key_unique";
DROP INDEX "products_slug_unique";
DROP INDEX "category_idx";
DROP INDEX "source_idx";
DROP INDEX "external_product_idx";
DROP INDEX "fulfillment_provider_idx";
DROP INDEX "listed_idx";
DROP INDEX "public_key_idx";
DROP INDEX "slug_idx";
DROP INDEX "external_provider_idx";
ALTER TABLE `products` ALTER COLUMN "public_key" TO "public_key" text NOT NULL;
CREATE INDEX `order_items_order_idx` ON `order_items` (`order_id`);
CREATE INDEX `order_items_product_idx` ON `order_items` (`product_id`);
CREATE INDEX `order_items_variant_idx` ON `order_items` (`variant_id`);
CREATE INDEX `orders_user_idx` ON `orders` (`user_id`);
CREATE INDEX `orders_checkout_session_idx` ON `orders` (`checkout_session_id`);
CREATE INDEX `orders_fulfillment_ref_idx` ON `orders` (`fulfillment_reference_id`);
CREATE INDEX `orders_status_idx` ON `orders` (`status`);
CREATE INDEX `pc_product_idx` ON `product_collections` (`product_id`);
CREATE INDEX `pc_collection_idx` ON `product_collections` (`collection_slug`);
CREATE INDEX `product_id_idx` ON `product_images` (`product_id`);
CREATE INDEX `type_idx` ON `product_images` (`type`);
CREATE INDEX `variant_product_idx` ON `product_variants` (`product_id`);
CREATE INDEX `variant_sku_idx` ON `product_variants` (`sku`);
CREATE INDEX `variant_external_idx` ON `product_variants` (`external_variant_id`);
CREATE UNIQUE INDEX `products_public_key_unique` ON `products` (`public_key`);
CREATE UNIQUE INDEX `products_slug_unique` ON `products` (`slug`);
CREATE INDEX `category_idx` ON `products` (`category`);
CREATE INDEX `source_idx` ON `products` (`source`);
CREATE INDEX `external_product_idx` ON `products` (`external_product_id`);
CREATE INDEX `fulfillment_provider_idx` ON `products` (`fulfillment_provider`);
CREATE INDEX `listed_idx` ON `products` (`listed`);
CREATE INDEX `public_key_idx` ON `products` (`public_key`);
CREATE INDEX `slug_idx` ON `products` (`slug`);
CREATE INDEX `external_provider_idx` ON `products` (`external_product_id`,`fulfillment_provider`);
ALTER TABLE `products` ALTER COLUMN "slug" TO "slug" text NOT NULL;